add command-line option for format-zfs

diff --git a/scripts-into-archiso/format-zfs b/scripts-into-archiso/format-zfs
--- a/scripts-into-archiso/format-zfs
+++ b/scripts-into-archiso/format-zfs
@@ -1,33 +1,37 @@
 #! /bin/bash
 
-# default will be archiso if you have boot on my iso, change it.
-ZFS_NAME=${1:-}
-
-# Edit here, with full path.
-DISK_ZFS="${2:-}"
-
-# If you want create user directory now, set a name.
-HOME_USERNAME="${3:-}"
-
-# We create swap ?
-DISK_SWAP="yes"
-
-# Swap Size in Gigabyte
-SWAP_SIZE="4G"
-
-# For old HDD with sector size of 512, set to "9" (2^9=512)
-ASHIFT_VALUE="12"
-
-# Temp directory where you install gentoo.
-TMP_MOUNT="/mnt"
-
-# U can let default here.
-ROOT_NAME="gentoo"
+ZFS_NAME="${ZFS_NAME:-rpool}"
+DISK_ZFS="${DISK_ZFS:-}"
+HOME_USERNAME="${HOME_USERNAME:-}"
+DISK_SWAP="${DISK_SWAP:-}"
+SWAP_SIZE="${SWAP_SIZE:-4G}"
+ASHIFT_VALUE="${ASHIFT_VALUE:-9}"
+TMP_MOUNT="${TMP_MOUNT:-/mnt}"
+ROOT_NAME="${ROOT_NAME:-gentoo}"
+DATABASE_PSQL="${DATABASE_PSQL:-}"
+DATABASE_MSQL="${DATABASE_MSQL:-}"
 
 function howto() {
-    echo "call $0 zfs_name zfs_disk home_name";
-    echo "example: $0 zfsDark /dev/disk/by-id/ata-ST9500423AS_S2V0QX6A bob"
-    echo "if param 'bob' is omit, user directory will not be created now."
+    cat <<- END
+
+    -H  -  Is /home/<name>, default not created
+    -z  -  zpool name, default is 'rpool' (yep... u want change that)
+    -d  -  disk or partition here in /dev/disk/by-id/
+    -s  -  Enable swap, default not created
+    -S  -  Size of swap in gigabyte with 'G' like '2G', '3G', 4G', default is 4G
+    -a  -  Enable Advanced Format disk if comptatible with sector size of 4096 byte (12^2=4096).
+    -m  -  work directory, must be empty, default in /mnt
+    -r  -  name of system, default is 'gentoo'
+    -P  -  Create postgresql directory now, default no
+    -M  -  Create Mysql directory now, default no
+    -v  -  print help
+    -h  -  print help too
+
+Examples:
+$0 -H ninja -z rpool -s -S 2G -a -d /dev/disk/by-id/ata-ST9500423AS_S2V0QX6A
+$0 -z improbable_name_for_zpool -d /dev/disk/by-id/ata-ST9500423AS_S2V0QX6A-part3
+END
+    exit ${1}
 }
 
 function isEmpty() {
@@ -36,8 +40,8 @@ function isEmpty() {
 }
 
 function ctrlParameter() {
-    if [ -z $ZFS_NAME ] ; then howto; return 1; fi
-    if [ -z $DISK_ZFS ] ; then howto; return 1; fi
+    if [ -z $ZFS_NAME ] ; then howto 1; fi
+    if [ -z $DISK_ZFS ] ; then howto 1; fi
     if [ ! -d $DISK_ZFS ] && [ ! -L $DISK_ZFS ] ; then 
         echo "Disk, partition not exist"; return 1;
     fi
@@ -74,10 +78,16 @@ function addVar() {
         ${ZFS_NAME}/var/cache || return 1
     zfs create -o com.sun:auto-snapshot=false -o exec=on \
         -o compression=off -o sync=disabled ${ZFS_NAME}/var/tmp || return 1
-    #zfs create -o recordsize=8k -o mountpoint=/var/lib/postgresql \
-    #    ${ZFS_NAME}/var/postgres || return 1
-    #zfs create -o recordsize=16k -o mountpoint=/var/lib/mysql \
-    #    ${ZFS_NAME}/var/mysql || return 1
+    if [ $DATABASE_PSQL ] ; then
+        zfs create -o recordsize=8k -o mountpoint=/var/lib/postgresql \
+            ${ZFS_NAME}/var/postgres || return 1
+        echo "postgresql created"
+    fi
+    if [ $DATABASE_MSQL ] ; then 
+        zfs create -o recordsize=16k -o mountpoint=/var/lib/mysql \
+            ${ZFS_NAME}/var/mysql || return 1
+        echo "mysql created"
+    fi
     echo "var/{log,cache,tmp} created"
 }
 
@@ -103,15 +113,18 @@ function addOpt() {
     #zfs create ${ZFS_NAME}/opt/musics || return 1
     #zfs create ${ZFS_NAME}/opt/games || return 1
     #zfs create ${ZFS_NAME}/opt/backups || return 1
+    #zfs create ${ZFS_NAME}/opt/x86system || return 1
     echo "opt created"
 }
 
 function addSwap() {
-    zfs create -V ${SWAP_SIZE} -b $(getconf PAGESIZE) \
-        -o logbias=throughput -o sync=always \
-        -o primarycache=metadata \
-        -o com.sun:auto-snapshot=false ${ZFS_NAME}/swap || return 1
-    echo "swap created"
+    if [ $DISK_SWAP ] ; then
+        zfs create -V ${SWAP_SIZE} -b $(getconf PAGESIZE) \
+            -o logbias=throughput -o sync=always \
+            -o primarycache=metadata \
+            -o com.sun:auto-snapshot=false ${ZFS_NAME}/swap || return 1
+        echo "swap created"
+    fi
 }
 
 function MakeTheJob() {
@@ -125,6 +138,30 @@ function MakeTheJob() {
     if ! addOpt ; then echo "Problem with opt"; return 1; fi
     if ! addSwap ; then echo "Problem with swap"; return 1; fi
 }
+
+OPTERR=0
+
+while getopts 'H:z:d:sS:am:r:PMvh' arg ; do
+    case "${arg}" in
+        H ) HOME_USERNAME="${OPTARG}" ;;
+        z ) ZFS_NAME="${OPTARG}" ;;
+        d ) DISK_ZFS="${OPTARG}" ;;
+        s ) DISK_SWAP=1 ;;
+        S ) SWAP_SIZE="${OPTARG}" ;;
+        a ) ASHIFT_VALUE=12 ;;
+        m ) TMP_MOUNT="${OPTARG}" ;;
+        r ) ROOT_NAME="${OPTARG}" ;;
+        P ) DATABASE_PSQL=1 ;;
+        M ) DATABASE_MSQL=1 ;;
+        v | h) howto 0 ;;
+        *)
+            echo "Invalid argument '${arg}'"
+            howto 1
+            ;;
+    esac
+done
+
+shift $(($OPTIND - 1))
 
 if MakeTheJob ; then
     echo "Format Success"
